### ISSUE TITLE
Return binary

### ISSUE THREAD

**Issue by Burnett01** [whitef0x0/node-lepton#1]
First of all nice wrapper.
While checking the code I noticed that both functions (compress, decrompress) don't return a binary blob as described in the readme: 

> "These functions takes a callback that returns an error object and the output in form of a binary file blob."

All it returns is "null".  Is it possible to return a binary?

Cheers, Burnett

**Comment by whitef0x0** [comment]
@Burnett01 just added this.

**Comment by Burnett01** [comment]
Cheers @whitef0x0
